name: run install playbook
on: 
    push:
      branches: [ main ]
jobs:
    install:
      runs-on: self-hosted #switch to "ubuntu-latest" if applicable
      steps:
        
        - name: git checkout
          uses: actions/checkout@v4
        
        - name: run playbook
          working-directory: ./ansible-dev
          run: ansible-playbook install-playbook.yml 
      